Make Network always contain the always-pulse
HeinrichApfelmus/reactive-banana pull request #242
Opened 2022-01-16 17:34 UTC by mitchellwrosen

This PR replaces the

```haskell
nAlwaysP :: Maybe (Pulse ())
```

field of `Network` with

```haskell
nAlwaysP :: Pulse ()
```

and propagates that change around the codebase.

Previously, when compiling a network, we checked to see whether it had an always-pulse, and built it if not.

In this PR, we instead just create the always-pulse when initializing an empty network in IO.

2022-01-16 19:09 UTC, ocharles approved these changes
I'm in favor of this! It eliminates a `case` that occurs every time we step the network. This is minor, but a nice little win

2022-01-16 19:11 UTC, ocharles commented on reactive-banana/src/Reactive/Banana/Prim/Compile.hs
> +compile m (Network time1 outputs1 theAlwaysP) = do
I would recommend using record syntax (`NamedFieldPuns` would be my preference, too).

2022-01-16 21:06 UTC, HeinrichApfelmus requested changes
Thanks Mitchell! 😊 What Ollie said, I'm in favor as well, with the little change.

2022-01-17 09:20 UTC, HeinrichApfelmus commented on reactive-banana/src/Reactive/Banana/Prim/Compile.hs
> +compile m Network {nTime, nOutputs, nAlwaysP} = do
```suggestion
compile m Network{nTime, nOutputs, nAlwaysP} = do
```

It's probably a matter of taste, but I like to leave no space between the constructor and the curly braces, lest they can be confused for two separate arguments.

2022-01-17 09:20 UTC, HeinrichApfelmus approved these changes

2022-01-18 03:26 UTC, merged